### ISSUE TITLE
About feat_size?

### ISSUE THREAD

**Issue by hizhangp** [miguelvr/dropblock#10]
[Here](https://github.com/miguelvr/dropblock/blob/master/dropblock/dropblock.py#L45), *feat_size* should be *sqrt(width * height)* ?

**Comment by miguelvr** [comment]
can you point me to the reference in the paper? feat_size is the number of features maps, thus it is the number of output channels of the convolution

**Comment by miguelvr** [comment]
It is stated in the paper:

> The size of valid seed region is (feat_size − block_size + 1)^2 where feat_size is the size of the feature
map.

feature map is usually the number of output channels from the convolution.

**Comment by hizhangp** [comment]
The paper says "*The size of valid seed region is (feat_size − block_size + 1)^2 where feat_size is the size of feature map*"，it matches Figure 2.

**Comment by hizhangp** [comment]
And *block_size* means the height and width of the mask, so *feat_size* should be the width and height of the feature map.

**Comment by miguelvr** [comment]
ok, so feat_size is relative to one feature map... that makes more sense.
and block_size is just one side of the block.

Alright, I'll make a PR with those changes.

But I'll make a change on that equation, because it only takes care of square images.
