### ISSUE TITLE
ImportError: cannot import name 'DropBlock2D'

### ISSUE THREAD

**Issue by Redaimao** [miguelvr/dropblock#11]
python 3.6
pytorch 0.4.1
Collecting dropblock
  Downloading https://files.pythonhosted.org/packages/42/e9/ea1afa72c7114685e6e971e23d68151eea00de171c2c7a6b9872c600be33/dropblock-0.1.0-py3-none-any.whl
Requirement already satisfied: numpy in /data/guoxiaobao/Anaconda3/envs/pytorch/lib/python3.6/site-packages (from dropblock)
Collecting torch==0.4.1 (from dropblock)
  Downloading https://files.pythonhosted.org/packages/49/0e/e382bcf1a6ae8225f50b99cc26effa2d4cc6d66975ccf3fa9590efcbedce/torch-0.4.1-cp36-cp36m-manylinux1_x86_64.whl (519.5MB)
    100% |████████████████████████████████| 519.5MB 2.7kB/s
Installing collected packages: torch, dropblock
  Found existing installation: torch 0.4.0
    Uninstalling torch-0.4.0:
      Successfully uninstalled torch-0.4.0
Successfully installed dropblock-0.1.0 torch-0.4.1

Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dropblock import DropBlock2D
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'DropBlock2D'

how can I fix this problem?

**Comment by miguelvr** [comment]
install from master. the pip version is outdated, will update it soon
