### ISSUE TITLE
Convolution operation can be replaced by MaxPool

### ISSUE THREAD

**Issue by miguelvr** [miguelvr/dropblock#16]
**Description:**

A maxpool operation can be used for the block mask calculation and might be more efficient to compute than a convolution.

**Comment by linzehui** [comment]
have you figured out how to replace convolution with maxpooling operation? I found convolution operation very slow.

**Comment by linzehui** [comment]
I tested two operation, MaxPooling can be much faster than Convolution.
An example may be like that:
mask = F.max_pool2d(input=mask[:, None, :, :],
                            kernel_size= (block_size, block_size),
                            stride=(1,1),
                            padding=(block_size ,block_size))

**Comment by miguelvr** [comment]
I know how to do it, just don't have much time to do it. Can you do a PR?
