### ISSUE TITLE
The variable x will be assigned to int type wrongly

### ISSUE THREAD

**Issue by Sampson-Lee** [miguelvr/dropblock#17]
https://github.com/miguelvr/dropblock/blob/0a1f2abc1cb34b9f6c7d3eaf7f232d038691bb58/dropblock/dropblock.py#L50

**Comment by miguelvr** [comment]
Can you elaborate?

**Comment by Sampson-Lee** [comment]
```
            if any([x <= 0 for x in mask_sizes]):
                raise ValueError('Input of shape {} is too small for block_size {}'
                                 .format(tuple(x.shape), self.block_size))

            # get gamma value
            gamma = self._compute_gamma(x, mask_sizes)
```
`if any([x <= 0 for x in mask_sizes]):` makes the variable x be assigned to int type, which results in mistakes in following code `gamma = self._compute_gamma(x, mask_sizes)`

**Comment by miguelvr** [comment]
I'm pretty sure that the variable `x` in the list comprehension is limited to its own scope, so it won't affect the input variable `x`

**Comment by Sampson-Lee** [comment]
thanks a lot， maybe the reason is that my python version is 2.7.

**Comment by miguelvr** [comment]
ah, yes... I didn't test with python 2.7, only with python 3.6, so I won't guarantee anything with that version.

I'll add a note to the README.
