### ISSUE TITLE
Segmentation?

### ISSUE THREAD

**Issue by bluesky314** [miguelvr/dropblock#18]
Can Dropblock be used for image segmentation tasks?

**Comment by miguelvr** [comment]
Sure, it is a regularization method, it is not specific to a task.

I would suggest to add it in the convolution feature extraction layer only.

**Comment by Eric2Hamel** [comment]
When you say to only add it in the convolution feature extraction layer only. I just want to make sure I understand correctly what you meant. Did you mean (if I take the U-Net as an example):
1. Single layer at the end of the encoder (that makes the hidden feature representation).
2. All the layer of the encoder of the segmentation model (responsible to extract feature from the image)
3. Layers of the encoder and decoder of the segmentation model (all hidden layers) (except the last one responsible for the prediction).

Thank you very much,
