### ISSUE TITLE
scheduled dropblock?

### ISSUE THREAD

**Issue by twmht** [miguelvr/dropblock#2]
Hi,

did you implement `scheduled dropblock` as mentioned in the paper?

>  In our experiments, we use a linear scheme of decreasing the value ofkeep_prob, which tends to work well across many hyperparameter settings. This linear scheme issimilar to ScheduledDropPath

**Comment by miguelvr** [comment]
Hey,

Not yet, but it is in the todo list in the README (unchecked)

However I am not sure how the ideal implementation would go, as you need to keep track of the number of iterations / epochs.

So it might be a better if the user manages that. I'll try to come up with something nevertheless 

Miguel

**Comment by twmht** [comment]
@miguelvr 

Maybe you can write a example about how to manage `scheduled dropblock`?

**Comment by miguelvr** [comment]
Yes, definetely! I will try to do that soon... An example is much needed anyway

**Comment by yunyundong** [comment]
Expect you release a version of `scheduled dropblock`
