### ISSUE TITLE
How to put in evaluation mode?

### ISSUE THREAD

**Issue by bluesky314** [miguelvr/dropblock#29]
Doing model.eval() does not shut off dropblock. How can I put it in evaluation mode for testing?

Thanks

**Comment by miguelvr** [comment]
This line checks if the Module is in evaluation mode. `model.eval()` does put `DropBlock` in evaluation mode. 
https://github.com/miguelvr/dropblock/blob/16a518a07869bd479be8434d0f57ace41cd26b41/dropblock/dropblock.py#L39
