### ISSUE TITLE
there is something wrong

### ISSUE THREAD

**Issue by yunyundong** [miguelvr/dropblock#3]
dropout=DropBlock2D(0.2,block_size=3)
input=torch.randn((1,1,8,8))
output=dropout(input)

   49             block_mask = self._compute_block_mask(mask)
     50             # apply block mask
---> 51             out = x * block_mask[:, None, :, :]
     52 
     53             # scale output

RuntimeError: The size of tensor a (8) must match the size of tensor b (9) at non-singleton dimension 3

**Comment by miguelvr** [comment]
I'll check it out in a few hours! Thanks for pointing it out, master isn't super stable yet

**Comment by miguelvr** [comment]
Should be fixed in commit f6598d8

please install again from the master, try it out and let me know!

**Comment by yunyundong** [comment]
```
b=torch.randn((200,1,9,9))
c=DropBlock2D(drop_prob=0.1,block_size=5)(b)
```
when width_to_crop and height_to_crop is equal to 0, there are bugs.

**Comment by miguelvr** [comment]
should be fixed now, let me know if you find any more issues.

**Comment by yunyundong** [comment]
```
if height_to_crop != 0 or width_to_crop != 0:
            block_mask = block_mask[:, :, :-height_to_crop, :-width_to_crop]

```
if one of them is equal to zero, the expression will report a bug.
In addition,

**Comment by miguelvr** [comment]
true... I found another edge case... Will have to have a further look.

try to use the stable release in the meanwhile

**Comment by yunyundong** [comment]
[this line](https://github.com/miguelvr/dropblock/blob/5ebc17922ceec70e8ce2170fc297089558c84be9/dropblock/dropblock.py#L63)
should be changed to 
```
block_mask = F.conv2d(mask[:, None, :, :],
                              torch.ones((mask.shape[1], 1, self.block_size, self.block_size)),
                              padding=self.block_size // 2 + 1)
```
namely, mask.shape[0] will be changed to mask.shape[1]

**Comment by miguelvr** [comment]
i noticed that already. I'm going to run more extensive tests today, with real data.

**Comment by miguelvr** [comment]
> [this line](https://github.com/miguelvr/dropblock/blob/5ebc17922ceec70e8ce2170fc297089558c84be9/dropblock/dropblock.py#L63)
> should be changed to
> 
> ```
> block_mask = F.conv2d(mask[:, None, :, :],
>                               torch.ones((mask.shape[1], 1, self.block_size, self.block_size)),
>                               padding=self.block_size // 2 + 1)
> ```
> namely, mask.shape[0] will be changed to mask.shape[1]

actually that is correct, the idea is to generate a mask of shape `(batch, 1, height, width)`, the features dimensions will be propagated

**Comment by miguelvr** [comment]
@yunyundong everything should be working as it should now
