### ISSUE TITLE
resnet-cifar10.py DropBlock scheduler

### ISSUE THREAD

**Issue by vadik6666** [miguelvr/dropblock#32]
In the benchmark there is

> * scheduled dropblock with block_size=5 and increasing drop_prob from 0.0 to 0.25 over 5000 iterations

At line https://github.com/miguelvr/dropblock/blob/master/examples/resnet-cifar10.py#L30 should it be 
`stop_value=0.25,`
?
Because currently in the code start_value=0 and stop_value=drop_prob, where drop_prob equals 0.0 (according to [config.yml)](https://github.com/miguelvr/dropblock/blob/master/examples/config.yml)). So DropBlock probability will be zero all the time, right?

**Comment by miguelvr** [comment]
yes, you're right.

I made experiments both with DropBlock and without. I guess I committed the config with no DropBlock
