### ISSUE TITLE
Pytorch Lightning as a back-end

### ISSUE THREAD

**Issue by williamFalcon** [miguelvr/dropblock#34]
Hi! check out Pytorch Lightning as an option for your backend! We're looking for awesome project implemented in Lightning.

Your project will be really easy to maintain on Lightning!

https://github.com/williamFalcon/pytorch-lightning

**Comment by miguelvr** [comment]
DropBlock provides generic nn.Module classes, if your framework supports it then you should be able to use it. I'm not looking for changing the code to tie it to a single framework

**Comment by williamFalcon** [comment]
the framework takes in generic nn.Modules
