### ISSUE TITLE
Where to put the dropblock in the ResNet network?

### ISSUE THREAD

**Issue by ZealACMer** [miguelvr/dropblock#35]
The description in the paper said "We found that applying DropbBlock
in skip connections in addition to the convolution layers increases the accuracy." but in the example file "resnet-cifar10.py" provided in this repo, the places for plugging DropBlock is different, thank you so much for your help.

**Comment by miguelvr** [comment]
The example is not meant to be a paper implementation reproduction, but rather an example of usage. 
You are free to use the DropBlock layer in different places in the ResNet model :)
