### ISSUE TITLE
The examples for using dropblock is different?

### ISSUE THREAD

**Issue by ZealACMer** [miguelvr/dropblock#36]
![image](https://user-images.githubusercontent.com/16794553/67749447-26711a00-fa68-11e9-9f83-ad19c882a31a.png)
In this part, the setting for drop_prob in DropBlock2D(block_size = 3, drop_prob = 0.) is "0.", and the stop_value is set to "0.25". But in the  example in resnet-cifar10.py(https://github.com/miguelvr/dropblock/tree/master/examples), the setting for drop_prob in DropBlock2D is shown as follows:
![image](https://user-images.githubusercontent.com/16794553/67749592-6afcb580-fa68-11e9-951c-be35949805b7.png)
The parameters drop_prob and stop_value both take the  idential setting by using "drop_prob", but in the first example, the setting for drop_prob and stop_value are 0. and 0.25 seperately. Which one is right? Thank you very much.

**Comment by miguelvr** [comment]
Both work, the drop_prob value will be overriden when using the linear scheduler
