### ISSUE TITLE
Would you please tell me how did you make certain the positive area of the mask keep still after max pooling operation ?

### ISSUE THREAD

**Issue by CoinCheung** [miguelvr/dropblock#39]
Hi, 

Thanks for your work on this !!! 

I am reading your code and found this line:  
https://github.com/miguelvr/dropblock/blob/7fb8fbfcb197a4bb57dc9193bcd6f375ff683f85/dropblock/dropblock.py#L63

It seems that you generated random mask, and then apply `max pooling` operation to it. However, after testing the `max pooling` operation, I found the number of `1`s in the mask cannot be kept same with this operation:
```
mask1 = torch.randint(0, 2, (1, 1, 256, 256)).float()
mask2 = F.max_pool2d(mask1, kernel_size=(5, 5), stride=1, padding=2)
print(mask1.sum())
print(mask2.sum())
```
The results is:
```
32715
65536
```
It seems that the proportion of the positive mask is changed with this operation. Would you please tell me how did you make sure the masked area is same after `max pooling` ?

**Comment by miguelvr** [comment]
Hi, 

That was indeed one of the biggest issues with implementing this technique.

The answer is indeed right there, in the surrounding lines of codes to where you linked.

It is basically controlled by the padding amount (`self.block_size // 2`) and by removing both a row and a column if necessary.

That operation is done here: https://github.com/miguelvr/dropblock/blob/7fb8fbfcb197a4bb57dc9193bcd6f375ff683f85/dropblock/dropblock.py#L68-L69

**Comment by CoinCheung** [comment]
Hi, 

Thanks for replying !! 

This is a simplified version of the code with `blocksize=5` and `prob=0.5`:
```
    p = 0.5
    blocksize = 5
    gamma = p / (blocksize ** 2)
    mask1 = (torch.rand(1, 1, 256, 256) < gamma).float()
    mask2 = F.max_pool2d(
            mask1, kernel_size=(blocksize, blocksize),
            stride=(1, 1), padding=blocksize//2)

    print(mask2.numel()) ## this is 256 x 256 = 65536
    print(mask2.sum()) ## this should be 65536 / 2 = 32768, but is actually around 26000
```
As I write in the comment of the code. The blocked area should be half of the spatial area of the tensor. In this case the tensor shape is `(1, 1, 256, 256)`, and thus the blocked area should be `256x256/2=32678`. But the area computed is always around 26000. Would you please tell me what did I miss here ?

**Comment by miguelvr** [comment]
You can look at what the mask and block_mask are expected to be in the unit tests.

Here is an example:
https://github.com/miguelvr/dropblock/blob/7fb8fbfcb197a4bb57dc9193bcd6f375ff683f85/tests/test_dropblock2d.py#L10-L25

**Comment by CoinCheung** [comment]
Hi, 

I just found that this method does not consider the overlap between the blocks. The overlap may cause the proportion of the masked pixels to be not same as assigned. For example, in my above code, the assigned proportion is 0.5, but since there are overlaps between each block, the total masked area is not 0.5 of the feature spatial area. Will this be OK with the implementation of dropblock ?

**Comment by miguelvr** [comment]
AFAIK there is nothing in the paper that refers to overlaps

**Comment by miguelvr** [comment]
The paper states

```
The main nuance of DropBlock is that there will be some overlapped in the dropped blocks, so
the above equation is only an approximation. In our experiments, we first estimate the keep_prob to
use (between 0.75 and 0.95), and then compute γ according to the above equation.
```
