### ISSUE TITLE
Use in segmentation. You suggest only for convolution feature extraction layer only. What do you mean?

### ISSUE THREAD

**Issue by Eric2Hamel** [miguelvr/dropblock#42]
When you say to only add it in the convolution feature extraction layer only. I just want to make sure I understand correctly what you meant. Did you mean (if I take the U-Net as an example):
1. Single layer at the end of the encoder (that makes the hidden feature representation).
2. All the layer of the encoder of the segmentation model (responsible to extract feature from the image)
3. Layers of the encoder and decoder of the segmentation model (all hidden layers) (except the last one responsible for the prediction).

Thank you very much,

_Originally posted by @Eric2Hamel in https://github.com/miguelvr/dropblock/issues/18#issuecomment-777068177_

**Comment by ShinewineW** [comment]
In the original paper, I think this DropBlock module is designed for information extraction path. Or the point 2 you mentioned above. However, you can also use this DropBlock module after any convolution layers' outputs, just like CBAM module. 
I have read one paper in 2020, which also use U-Net. That paper's structure called SA-UNet, the author used DropBlock in all convolution layers and got well results, you can try the same way. Or the point 3 you mentioned above.

**Comment by Eric2Hamel** [comment]
Thanks for you answer! Really clear!
